# Generated by Django 5.2.7 on 2025-11-01 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_calificacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['-fecha', '-hora'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_hora',
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
