# Generated by Django 5.2.7 on 2025-11-05 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0003_promocion_fecha_modificacion'),
        ('turnos', '0004_alter_turno_options_remove_turno_fecha_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='promocion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos', to='promociones.promocion'),
        ),
    ]
