# Generated by Django 5.2.7 on 2025-10-31 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promociones', '0001_initial'),
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='servicios.categoria'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='promociones', to='servicios.servicio'),
        ),
    ]
