# Generated by Django 5.2.7 on 2025-11-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
