# Generated by Django 5.2.6 on 2025-11-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promociones', '0003_promocion_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
