# Generated by Django 5.2.7 on 2025-11-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_alter_servicio_profesional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='fecha_actualizacion',
            new_name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='categoria',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
