# Generated by Django 5.2.7 on 2025-10-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('preferencias_cliente', 'Preferencias y Comportamientos de Cliente'), ('servicios_populares', 'Servicios Más Populares'), ('ingresos', 'Ingresos'), ('profesionales', 'Desempeño de Profesionales')], max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('datos_json', models.JSONField(help_text='Datos del reporte en formato JSON')),
            ],
            options={
                'verbose_name': 'Reporte',
                'verbose_name_plural': 'Reportes',
                'ordering': ['-fecha_generacion'],
            },
        ),
    ]
