# Generated by Django 5.2.7 on 2025-10-31 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaCancelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('horas_anticipacion', models.IntegerField(help_text='Horas de anticipación requeridas')),
                ('penalizacion_porcentaje', models.DecimalField(decimal_places=2, help_text='Porcentaje de penalización', max_digits=5)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política de Cancelación',
                'verbose_name_plural': 'Políticas de Cancelación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('dias_reembolso', models.IntegerField(help_text='Días para procesar el reembolso')),
                ('porcentaje_reembolso', models.DecimalField(decimal_places=2, help_text='Porcentaje a reembolsar', max_digits=5)),
                ('condiciones', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política de Reembolso',
                'verbose_name_plural': 'Políticas de Reembolso',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
